# SITE CONFIGURATION
title: jooot # your site title
author: Jow # You :P
paginate: 5
paginate_path: "/page:num/"

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://plus.google.com/
    - https://github.com/
    - https://keybase.io/



tagline: >
  Paper Suevey of Machine Learning

hero_img: posts/header1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email:  test@domain.example # email for form submission

twitter_username: test # replace with your_twitter_username or comment to remove link from footer
github_username:  TakeruEndo # replace with your_github_username or comment to remove link from footer
instagram_username: test # replace with your_instagram_username or comment to remove link from footer

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# service_worker: true
